name: "Feature request"
description: "Suggest an idea for Maki"
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for **Maki**! 🎯
        Please fill out the sections below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "A clear and concise description of what problem this feature would solve."
      placeholder: "Example: I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: altsolution
    attributes:
      label: "Alternative Solutions"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Relevant Context"
      description: "Add any other context, screenshots, or examples about the feature request here."
    validations:
      required: true

  - type: textarea
    id: simplicity
    attributes:
      label: "Does this feature align with Maki's focus on simplicity?"
      description: "Yes/No, because..."
    validations:
      required: true
