name: Build & publish images to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag the images (e.g., 1.0.0)"
        required: true
        type: string
      latest:
        description: "Also tag as latest"
        required: false
        type: boolean
        default: false

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      tags: |
        type=raw,value=${{ inputs.version }}
        type=raw,value=latest,enable=${{ inputs.latest }}
